---
apiVersion: apps/v1
kind: Deployment
metadata:
  mame: comments-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: comments-api
  template:
      metadata:
        labels:
           name: comment-api
      spec:
        containers:
        - name: application
          image: "alexisdevgrp/comments-api:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_PORT
              value: "25060"
            - name: DB_HOST
              value: "db-postgresql-lon1-20536-do-user-1074347-0.b.db.ondigitalocean.com"
            - name: DB_PASSWORD
              value: "nhw7ssu5c9ezvo4a"
            - name: DB_TABLE
              value: "defaultdb"
            - name: DB_USERNAME
              value: "doadmin"




